# Generated by Django 5.1.7 on 2025-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('mental_health', 'Mental Health'), ('heart_disease', 'Heart Disease'), ('covid19', 'Covid19'), ('immunization', 'Immunization')], max_length=50),
        ),
    ]
